Shopify/kubeaudit

.gitignore
Makefile

@JonPulsifer @klautcomputing Updated the makefile with more flags like building binary for linux, docker image etc.

Add more flags to makefile

---

README.md

Following labels are added:
- godoc
- test coverage
- go report card

Add some useful labels in README

---

README.md

Quick update to reflect our newest feature.

Update readme for manifest auditing

---

cmd/errors.go
cmd/runAsNonRoot.go
cmd/runAsNonRoot_test.go

Refactor runAsNonRoot to have named errors and better error messages

---

cmd/errors.go
cmd/securityContext.go
cmd/securityContext_test.go

Refactored security context tests to replace numbered errors with constants.

Refactored security context tests

---

Gopkg.lock
Gopkg.toml
cmd/kubernetes.go

Update all dependencies to current master

Fixes #41: Update all dependencies to the current master

---

cmd/automountServiceAccountToken.go
cmd/image.go
cmd/privileged.go
cmd/readOnlyRootFilesystem.go
cmd/runAsNonRoot.go
cmd/securityContext.go
cmd/util.go

- all occurrences of getKubeResources() renamed to getKubeResourcesManifest()
- new func getKubeResources() created in util.go to reduce code redundancy
- general code refactoring

Refactored code, added getKubeResources() in util

---

.travis.yml
Makefile
test.sh

Since cover.run seems to be done I switched us to codecov
for test.sh compare:
https://github.com/codecov/example-go

Get a code coverage badge

---

cmd/automountServiceAccountToken.go
cmd/image.go
cmd/privileged.go
cmd/runAsNonRoot.go
cmd/util.go

Refactor audit commands

---

.gitignore
cmd/util.go

Bug fix: -j works again

---

cmd/automountServiceAccountToken.go
cmd/image.go
cmd/privileged.go
cmd/runAsNonRoot.go
cmd/util.go

Revert "Refactor audit commands"

---

cmd/automountServiceAccountToken.go
cmd/image.go
cmd/privileged.go
cmd/readOnlyRootFilesystem.go
cmd/runAsNonRoot.go
cmd/securityContext.go

For more context refer: https://stackoverflow.com/questions/40326723/go-vet-range-variable-captured-by-func-literal-when-using-go-routine-inside-of-f

Make govet happy

---

cmd/image_test.go
cmd/test_util.go

Refactor test_util into one function

---

README.md

Update readme with info about the allowPrivilegeEscalation audit

Add allowpe to readme

---

Makefile
test.sh

Nice to way to visualize which portion of code is not tested.

Add a rule in makefile to show coverage in HTML format

---

Gopkg.lock
cmd/autofix_test.go
cmd/cap_set.go
cmd/cap_set_test.go
cmd/capabilities.go
fixtures/autofix-fixed.yml

Sorts capabilities to prevent stochastic output

Sort capabilities

---

cmd/privileged.go

Remove erroneous comment
Update short help description to reflect command

Update privileged.go documentation

---

cmd/allowPrivilegeEscalation.go
cmd/automountServiceAccountToken.go
cmd/privileged.go
cmd/readOnlyRootFilesystem.go
cmd/result.go
cmd/runAsNonRoot.go
fixtures/allow_privilege_escalation_misconfigured_allow.yml
fixtures/allow_privilege_escalation_true_allowed.yml
fixtures/capabilities_misconfigured_allow.yml
fixtures/capabilities_some_allowed.yml
fixtures/privileged_misconfigured_allow.yml
fixtures/privileged_true_allowed.yml
fixtures/read_only_root_filesystem_false_allowed.yml
fixtures/read_only_root_filesystem_misconfigured_allow.yml
fixtures/run_as_non_root_false_allowed.yml
fixtures/run_as_non_root_misconfigured_allow.yml
fixtures/service_account_token_misconfigured_allow.yml
fixtures/service_account_token_true_allowed.yml

Make labels conform to standards

---

cmd/k8sruntime_util.go
cmd/k8sruntime_util_test.go
cmd/util.go

Fix for this issue: https://github.com/Shopify/kubeaudit/issues/87

Fixes #87 autofix

---

cmd/kubernetes.go

Fixes #96 
@krishshenoy Can you confirm this fixes your issue?

import oidc auth-provider to support oidc based kubconfig

---

cmd/cronjob_test.go
cmd/k8sruntime_util.go
cmd/types.go
fixtures/cronjob-fixed.yml
fixtures/cronjob.yml

I just wanted to `autofix` a CronJob and while it didn't error or explode it also did nothing meaningful. So I fixed that!
Let me know what you think.

Add kind CronJob

---

README.md

A couple of ordered lists weren't incrementing.

Fix readme list numbering

---

cmd/capabilities.go
cmd/capabilities_test.go
fixtures/capabilities_dropped_all.yml

Fixes #110 
@Tmlja1Jldmlu hopefully this fix the false positive that you were observing.
Thanks for filing the issue. 😄

capabilities: Fix a false positive when all capabilities dropped

---

Makefile

Use compatible version comparison.

---

Gopkg.lock
cmd/allowPrivilegeEscalation.go
cmd/allowPrivilegeEscalation_fixes.go
cmd/appArmor.go
cmd/appArmor_fixes.go
cmd/autofix.go
cmd/automountServiceAccountToken.go
cmd/automountServiceAccountToken_fixes.go
cmd/capabilities.go
cmd/capabilities_fixes.go
cmd/image.go
cmd/k8sruntime_util.go
cmd/limits.go
cmd/privileged.go
cmd/privileged_fixes.go
cmd/readOnlyRootFilesystem.go
cmd/readOnlyRootFilesystem_fixes.go
cmd/runAsNonRoot.go
cmd/runAsNonRoot_fixes.go
cmd/seccomp.go
cmd/seccomp_fixes.go
cmd/seccomp_fixes_test.go
cmd/securitycontext_fixes.go
cmd/test_util.go
cmd/types.go
cmd/util.go

Adds a resource type so that we don't have to write `resource k8sRuntime.Object` everywhere all the time.

Add Resource type

---

CODE_OF_CONDUCT.md

This change fixes the email that code of conduct violations should be reported to.

fix Code of Conduct email

---

cmd/autofix_util.go
cmd/networkPolicies_fixes_test.go
fixtures/namespace_missing_default_deny_netpol-fixed.yml

Use "ports" or "from" as identifying key for "ingress"

---

cmd/autofix.go
cmd/autofix_util.go
fixtures/autofix-namespace-missing-default-deny-netpol-fixed.yml
fixtures/preserve_comments-fixed_v2.yml

Fix: Starting Files with YAML Separator

---

cmd/root.go

Noticed when trying out kubeaudit for the first time.

cmd: fix copy/paste on flag -dropCapConfig description

---

cmd/autofix.go
cmd/autofix_util.go
cmd/test_util.go
fixtures/autofix-all-resources-fixed_v1.yml
fixtures/autofix-fixed_v1.yml
fixtures/autofix-namespace-missing-default-deny-netpol-fixed.yml
fixtures/autofix-unsupported-fixed_v1.yml
fixtures/preserve_comments-fixed_v2.yml
fixtures/preserve_comments_v2.yml

remove NULL status and creationTimestamp ( Issue #184)

---

.github/autolabeler.yml
.github/probots.yml
.github/welcome.yml

Probot Features

---

test.sh

[WIP] [Fix] Codecov coverage.txt Results

---

README.md
cmd/networkPolicies.go

Egress debug messages were incorrect

fix debug message bug

---

cmd/autofix_util.go
fixtures/autofix-all-resources-fixed_v1.yml
fixtures/autofix-all-resources_v1.yml
fixtures/image_tag_missing_v1.yml
go.mod
go.sum

This along with https://github.com/Shopify/yaml/pull/4, should fix both issues #201  and #202,  then we can release v.0.5.3
closes #201 
closes #202

Remove creationTS for jobspec and fix 80 char line break

---

cmd/autofix_util.go
fixtures/autofix-all-resources-fixed_v1.yml
fixtures/autofix-all-resources_v1.yml

This PR matches host names correctly, refer to #205 for the issue
closes #205

[BUG FIX] Handles Issue 205

---

fixtures/autofix-all-resources-fixed_v1.yml
fixtures/autofix-all-resources_v1.yml
go.mod
go.sum

Thanks to @r6min  for [https://github.com/Shopify/yaml/pull/5],  comment marshalling is not bugged anymore 
closes #203

[BUG FIX] #203

---

README.md

Fixes link behind "config/caps" in the README.md

README: Updates link to config/caps

---

README.md

This is a temporary readme change while we investigate issue #224

go get doesn't work readme update

---

README.md
go.mod

[BUG FIX] 224 fix go get

---

cmd/k8sruntime_util.go
cmd/types.go
cmd/util.go
fixtures/autofix-all-resources-fixed_v1.yml
fixtures/autofix-all-resources_v1.yml
fixtures/podtemplate_v1.yml

Support podtemplates

---

cmd/util.go

Log incorrect or missing kubeaudit file

Log missing or wrong kubeconfig file

---

README.md
auditors/asat/fixtures/service-account-token-redundant-override.yml
auditors/asat/fixtures/service-account-token-true-allowed.yml
auditors/capabilities/fixtures/capabilities-some-allowed-multi-containers-mix-labels.yml
auditors/capabilities/fixtures/capabilities-some-allowed-multi-containers-some-labels.yml
auditors/capabilities/fixtures/capabilities-some-allowed.yml
internal/override/override.go

Establishes expectations for the result severity levels and changes the severity of overridden results to comply.
`Error`: A security issue
`Warning`: A best practice recommendation
`Info`: Informational, no action required. This includes results that are overridden

Change overridden result severity from warning to info

---

.goreleaser.yml

Adapt goreleaser config so it builds windows binaries too.
- [X ] New feature :sparkles:

feat(gorelease): build native windows binaries too

---

auditors/privileged/privileged.go

Fix typo in `PrivilegedNil` rule description
N/A

fix: typo in PrivilegedNil rule description

---

auditors/image/image.go

These where the only rule description missing.

chore(docs): add rules description

---

.deepsource.toml
auditors/image/image.go
auditors/privesc/privesc.go
internal/yaml/yaml.go

Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/kubeaudit/issues/?category=recommended).
- Remove unnecessary comparison with bool
- Combine multiple `append`s into a single call
- Fix check for empty string
- Add .deepsource.toml config

[Improvement] Fixed code quality issues 

---

internal/k8s/client.go

Add auth support for azure, exec, oidc, openstack

---

docs/release.md

Adds instructions on how to make a release.

[docs]: Add release instructions

---

cmd/commands/capabilities.go
docs/auditors/capabilities.md

This PR changes the flag formatting for the capabilities auditor so it's consistent with all other flags  (with dashes, rather than camel case)

flag formatting

---

README.md
docs/auditors/capabilities.md

Fixes docs on how to allow caps errors to be ignored by passing in the `allowAddList` field.

Updates readme with correct field name

---

.travis.yml
README.md

Removes Codecov bash uploader use as it is deprecated.

Remove Codecov

---

pkg/k8s/types.go

Small Pr to support the parsing of Server Specs

Support parsing for server specs

---

docs/cluster.md

Fix kubeaudit job namespace in example of running kubeaudit with RBAC and in a specific namespace.

:bug: Fix kubeaudit job namespace in cluster example

---

.github/welcome.yml

Fix PR welcome message to contributing guidelines.

:bug: Fix PR welcome message to contributing guidelines

---

goreleaser.Dockerfile

Fixes typo in the go version from `17` to `1.17`

🩹 Fix docker go version

---

auditors/mounts/mounts.go
config/config.yaml
docs/auditors/mounts.md

Update list of sensitive paths from Falco rules, adds containerd :sparkles:
Not tested

feat(mounts): update list of sensitive paths from Falco, adds containerd :sparkles:
