Shopify/kubeaudit

.travis.yml, README.md
This addresses #4 by changing the url and dropping support for `go1.8.3`
=> Get the nice Travis status back

README.md, cmd/version.go
In order to print the kubeaudit's current version, a new command has been added to kubeaudit
```sh
./kubeaudit version
INFO[0000] Kubeaudit                                     Version=0.1.0
```
=> New command to print version

cmd/image.go, cmd/image_test.go, cmd/util.go
This is a minor patch in order to fix the confusion between image tag and image name in the logs while auditing against some image.
=> image: Fix confusion between image name and image tag

cmd/image.go
The `Example usage` for the `kubectl image` command is incorrect. The `-i` or `--flags` are required.
=> The "kubectl image" command requires the "-i" or "--image" flags.

.travis.yml, Makefile, cmd/version.go, glide.lock, glide.yaml, vendor/github.com/hashicorp/go-version/.travis.yml, vendor/github.com/hashicorp/go-version/LICENSE, vendor/github.com/hashicorp/go-version/README.md, vendor/github.com/hashicorp/go-version/constraint.go, vendor/github.com/hashicorp/go-version/constraint_test.go, vendor/github.com/hashicorp/go-version/version.go, vendor/github.com/hashicorp/go-version/version_collection.go, vendor/github.com/hashicorp/go-version/version_collection_test.go, vendor/github.com/hashicorp/go-version/version_test.go
- First commit: Updating dependencies in order to `hashicorp/go-version` in order to complete #2 
- Second commit: Always check `kubeaudit` version is consistent with semantic versioning.
=> deps: Update dependencies in order to include hashicorp/go-version

cmd/automountServiceAccountToken.go, cmd/image.go, cmd/privileged.go, cmd/readOnlyRootFilesystem.go, cmd/root.go, cmd/runAsNonRoot.go, cmd/securityContext.go, cmd/securityContext_test.go, cmd/util.go, fakeaudit/utils.go
I started working on the new feature to audit config files passed as a command line argument. Right now it works only for securityContext. It needs to be ported to other features too.
I am not happy about of lot of stuff in this PR mostly regarding code quality. Need lot of interface love.  Sorry I was in hurry could not make code more clear.
It is just a proof of concept that is possible to do so.
=> new feature: audit manifest file from command line args

cmd/image.go, cmd/image_test.go
As per the documentation string:
```
An INFO log is given when a container has a matching image:tag
An ERROR log is generated when a container does not match the image:tag
```
This is not what is happening. Currently, it only prints the `ERROR` log. This pull request updates the `kubectl image` command to also print an `INFO` log when the `image:tag` matches.
=> Print INFO message for matching image:tag

cmd/automountServiceAccountToken.go, cmd/image.go, cmd/kubernetes.go, cmd/privileged.go, cmd/privileged_test.go, cmd/readOnlyRootFilesystem.go, cmd/readOnlyRootFilesystem_test.go, cmd/runAsNonRoot.go, cmd/runAsNonRoot_test.go, cmd/securityContext.go, cmd/securityContext_test.go, cmd/util.go, fakeaudit/fakeDaemonSets.go, fakeaudit/fakeDeployments.go, fakeaudit/fakePods.go, fakeaudit/fakeReplicationControllers.go, fakeaudit/fakeStatefulSets.go, fakeaudit/utils.go
#15 Allowed us to audit maifests, unfortunately it only allowed for one resource to be present in the `manifest.yaml`
In this PR the functionality to audit manifest files that contain more than one resource is introduced.
=> New feature: audit yaml files with more than 1 resource

cmd/errors.go, cmd/image.go, cmd/image_test.go, cmd/util.go
This is the first step towards error handling. Which lead me into a bit of a refactoring trip field trip.
Anyways, this enables us to easily integrate the functionality that @marc-barry wants to introduce with https://github.com/Shopify/kubeaudit/pull/20 but in a nicer way. I will update the PR once this one is merged.
This removes some splitting code with wasn't nice and `os.Exit(1)` from a function where it's way too late to do an `os.Exit` for a cmd line param check.
=> Refactor image

cmd/errors.go, cmd/readOnlyRootFilesystem.go, cmd/readOnlyRootFilesystem_test.go
This refactors read only root FS a little and introduces named errors here as well. Some better error messages are in here as well.
Note: We need to merge #26 before this.
=> Refactor ro root fs

cmd/image.go, cmd/kubernetes.go, cmd/networkPolicies.go, cmd/privileged.go, cmd/readOnlyRootFilesystem.go, cmd/runAsNonRoot.go, cmd/securityContext.go, cmd/types.go, cmd/util.go
Introduce internal types so that we can have better level of abstraction and it would be easier to changes those types when some internal kubernetes type changes. For example deployment is moving from v1 to v2.
PS: This is only possible because go 1.9 supports type aliasing
=>  types: Create internal types instead of using kubernetes types

.travis.yml, cmd/kubernetes.go, cmd/version.go
Closes #43
Only shows server/client info during `version` command instead of when using `-l` flag.
=> Only show version info during version command

cmd/automountServiceAccountToken.go, cmd/automountServiceAccountToken_test.go, cmd/image.go, cmd/image_test.go, cmd/privileged.go, cmd/privileged_test.go, cmd/readOnlyRootFilesystem.go, cmd/readOnlyRootFilesystem_test.go, cmd/runAsNonRoot.go, cmd/runAsNonRoot_test.go, cmd/securityContext.go, cmd/securityContext_test.go, cmd/util.go
Fixes https://github.com/Shopify/kubeaudit/issues/52. I've refactored it to in a way that I think is cleaner because:
- The WaitGroup usage is all in one place, one can see all the calls instead of having it on diff functions
- No global WaitGroup
Let me know what you think.
=> Refactor, clear up WaitGroup usage

cmd/automountServiceAccountToken.go, cmd/capabilities.go, cmd/image.go, cmd/privileged.go, cmd/readOnlyRootFilesystem.go, cmd/runAsNonRoot.go, cmd/util.go
Fixes channel issues causing https://github.com/Shopify/kubeaudit/pull/61, as well as further refactoring the `runAudit` and `runImageAudit` util functions into one single function.
=> Refactor audit command run code into a util function

cmd/allowPrivilegeEscalation.go, cmd/allowPrivilegeEscalation_test.go, cmd/errors.go, fixtures/allow_privilege_escalation_nil.yml, fixtures/allow_privilege_escalation_true.yml
Closes #23 . This PR creates a new audit that makes sure that `AllowPrivilegeEscalation` is false.
=> Create audit for AllowPrivilegeEscalation

cmd/allowPrivilegeEscalation.go
When `AllowPrivilegeEscalation` is nil privilege escalation is allowed, so we should error instead of warning.
=> Error when AllowPrivilegeEscalation is nil

cmd/kubernetes.go, cmd/namespace_test.go, cmd/root.go, cmd/test_util.go, cmd/util.go
Limiting auditing to a namespace can be useful in some cases.
I propose to add the `-n` or `--namespace` option to do this.
```
kubeaudit -l sat -n default
ERRO[0000] Default serviceAccount with token mounted. Please set AutomountServiceAccountToken to false  KubeType=deployment Name=redis Namespace=default
```
If nothing is indicated, all namespaces are taken into account as currently.
What do you think about this option?
=> Auditing for specific namespace (with -n or --namespace option)

cmd/result.go, cmd/util.go
This breaks `Result` out of the `util.go` into its own file `result.go` and refactors `runAudit` to be more modular and reusable.
=> Break type result out of util

cmd/allowPrivilegeEscalation.go, cmd/automountServiceAccountToken.go, cmd/capabilities.go, cmd/image.go, cmd/kubernetes.go, cmd/limits.go, cmd/namespace_test.go, cmd/privileged.go, cmd/readOnlyRootFilesystem.go, cmd/runAsNonRoot.go, cmd/test_util.go, cmd/util.go
This is an attempt to switch away from all our internal types to `runtime.Objects`. Let me know what you think.
=> Refactor util.go, deletes all kubeaudit types

cmd/allowPrivilegeEscalation_test.go, cmd/automountServiceAccountToken_test.go, cmd/capabilities_test.go, cmd/image_test.go, cmd/limits_test.go, cmd/namespace_test.go, cmd/privileged_test.go, cmd/readOnlyRootFilesystem_test.go, cmd/runAsNonRoot_test.go, cmd/test_util.go
This PR enables our tests to ensure that only errors that were specified were thrown.
=> Add stricter check for audit tests

README.md
=> Add autofix to readme

README.md, cmd/all.go, cmd/all_test.go, cmd/autofix.go, cmd/image.go, cmd/util.go, fixtures/audit_all.yml
Adds `all` command, does what it says on the tin.
=> Add command to run ALL the audits

cmd/automountServiceAccountToken.go, cmd/capabilities.go, cmd/privileged.go, cmd/readOnlyRootFilesystem.go, cmd/runAsNonRoot.go
Some of the command examples for cobra commands are different from the actual commands. This PR fixes the inconsistencies and also adds a description to the caps command, which didn't have one.
=> Cmd match example

README.md, cmd/kubernetes.go, cmd/networkPolicies.go, cmd/root.go, cmd/util.go, cmd/version.go
This changes the default behaviour of kubeaudit so that it will automatically use the default local config from `$HOME/.kube/config` any time it's not running within a k8s container. You can still force it to use local config mode if it is running in a cluster by specifying `-c/--kubeconfig /config/path`.
The `-l` flag is no longer necessary, but you can still use it and it will behave as before so it doesn't break backwards compatibility. It will display a warning if you use it.
I moved the logging initialization to root so that formatting and level will be respected for all commands even if you don't call kubeClient(). 
Edit: fixing the version number and adding tests will be done in a separate PR.
=> Automatically detect local/cluster mode

Makefile, README.md
With kubectl v1.12.0 introducing [easy pluggability](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) of external functions, kubeaudit can be invoked as `kubectl audit` just by
- running `make plugin` and having $GOPATH/bin available in your path.
or
- renaming the binary to `kubectl-audit` and having it available in your path.
=> Kubectl plugin

.goreleaser.yml, Gopkg.lock, Makefile, build/ldflags.sh, cmd/kubernetes.go, cmd/kubernetes_test.go, cmd/root.go, cmd/version.go, cmd/version_test.go
A few releases in a row showed incorrect version numbers. This change will prevent that by automatically versioning builds based on the commit SHA and tag. For example:
```
./kubeaudit version
INFO[0000] Kubeaudit version BuildDate="2018-11-05T20:50:42000000000+0000" Commit=e5abb2c Version=v0.3.0
```
The version command will only output server version information if there is a kubernetes server to connect to (based on command switches and environment settings). This PR adds testing for the version command, to prevent issues like #112.
It also closes #115 by removing the attempt to display non-existent client version information.
=> Fix version

Makefile
Echo behaves differently in different shells. Some require -e to expand \n, but others don't have a -e switch. This change makes the version check compatible with most shells.
=> Use printf instead of echo to avoid shell incompatibility with -e.

Gopkg.lock, cmd/allowPrivilegeEscalation.go, cmd/autofix_test.go, cmd/image.go, cmd/limits.go, cmd/privileged.go, cmd/readOnlyRootFilesystem.go, cmd/runAsNonRoot.go, cmd/test_util.go
This fixes #141 
Turns out if you `break` out of your loop then you never get shit done 🙂 
Added a regression test. Turns out: deep equal from `deep` doesn't catch the difference, deep equal from `reflect` complains that they are not equal, so I serialize them, write them to file and compare the file contents.
=> Audit all containers

Gopkg.lock
The package go-cmp is no longer used, but it was still in Gopkg.lock. This removes it so that the state will be clean for the next release.
=> Remove unused go-cmp from Gopkg.lock.

cmd/automountServiceAccountToken_fixes_test.go, cmd/k8sruntime_util.go, cmd/test_util.go, fixtures/service_account_token_deprecated_multiple_resources_v1.yml
Kind words by Jon -
If serviceAccount is present, it should assume that serviceAccountName is also set and present because it's an alias (deprecated)
if there is no serviceAccount[Name] specified, it assumes `default` and uses the `default` SA token, which is not desirable in most multi-tenant circumstances, so automountServiceAccountToken: false should then be applied (edited) 
To use a non-default service account, simply set the spec.serviceAccountName field of a pod to the name of the service account you wish to use.
so realistically, if serviceAccount != default, then it should replace it with serviceAccountName instead
if it is default, remove it and add automount false
closes #157 
Tests -
=> add replacement for DSA to SA

cmd/automountServiceAccountToken.go, cmd/automountServiceAccountToken_test.go, fixtures/service_account_token_true_and_default_name_v1.yml
Ref #168, When `automountServiceAccountToken` is set to true and `serviceAccountName` is set to be `default` kubeaudit didn't throw an error as it should, this issue has been addressed in this PR.
closes #168
=> Fix default SA name bug

.travis.yml, Makefile
Ref #170 
Go 1.12 is now released and `kubeaudit` should be compatible with it, so we need to replace Go 1.10 with Go 1.12 for our CI environment.
closes #170
=> Use Go 1.12

cmd/automountServiceAccountToken_fixes_test.go, cmd/k8sruntime_util.go, cmd/types.go, cmd/util.go, fixtures/apparmor_annotation_missing_multiple_resources_v1.yml, fixtures/service_account_token_deprecated_multiple_resources_v1.yml, fixtures/service_account_token_true_and_no_name_multiple_resources_v1.yml
This PR add's support for DaemonSet apps/v1beta2 resource - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#daemonset-v1beta2-apps
closes #183
=> Support DaemonSet apps/v1beta2

README.md, cmd/errors.go, cmd/networkPolicies.go, cmd/networkPolicies_test.go, cmd/util.go, fixtures/allowed_namespace_missing_default_deny_egress_netpol.yml, fixtures/allowed_namespace_missing_default_deny_ingress_netpol.yml, fixtures/allowed_namespace_missing_default_deny_netpol.yml
This PR adds support for Network Policy auditing overrides. 
closes #160
=> Namespace Network Policy Overrides

README.md, cmd/all.go, cmd/autofix_util.go, cmd/config.go, cmd/errors.go, cmd/namespaces.go, cmd/namespaces_fixes.go, cmd/namespaces_fixes_test.go, cmd/namespaces_test.go, configs/allow_namespaces_from_config.yml, configs/kubeauditConfig.yaml, fixtures/host_IPC_true_allowed_v1.yml, fixtures/host_IPC_true_v1.yml, fixtures/host_PID_true_allowed_v1.yml, fixtures/host_PID_true_v1.yml, fixtures/host_network_true_allowed_v1.yml, fixtures/host_network_true_v1.yml, fixtures/namespaces_all_true_allowed_v1.yml, fixtures/namespaces_all_true_v1.yml, fixtures/namespaces_misconfigured_allow_v1.yml
This PR add support for a new type of check- Namespaces(nix)
Following fields are checked for in podSpec:
The use of host's networking | hostNetwork
The use of host’s PID namespace | hostPID
The use of host’s IPC namespace | hostIPC
By default, all hostNetwork, hostPIC, and hostPID are set to false. 
closes #46
=> [FEATURE] Audit Pod Namespace Nix

cmd/util.go
When using kubeaudit, I ran into a non-descriptive error `File is not a valid Kubernetes manifest`. 
To troubleshoot this issue, I edited the error log to report the underlying error, thought I would PR it back.
=> update File is not a valid kubernetes manifest to return underlying parsing error

cmd/autofix_test.go, cmd/autofix_util.go, fixtures/autofix-all-resources-fixed_v1.yml, fixtures/autofix-all-resources_v1.yml
The logic for matching ClusterRole.rules and Role.rules was removed as part of https://github.com/Shopify/kubeaudit/pull/206/files#diff-3fd80df8ad953804dabe08fbffd8999fL562. It was unrelated to the bug that PR was meant to fix. IngressSpec.rules does not have a `resources` field thus putting it back is not a regression.
=> Put back autofix logic for ClusterRole and Role

.github/PULL_REQUEST_TEMPLATE.md, .github/welcome.yml, README.md
Adds a link to the Contributor License Agreement in the Contributing section of the README!
This is a documentation change and doesn't require testing!
=> add CLA link to Contributing

README.md
Command line argument `--auditconfig` was wrong in docs
=> --auditConfig --> --auditconfig in docs

cmd/autofix.go, cmd/autofix_test.go, cmd/autofix_util.go, cmd/capabilities.go, cmd/root.go, cmd/util.go, fixtures/autofix-all-resources-fixed_v1.yml, fixtures/autofix-all-resources_v1.yml, fixtures/autofix-fixed_v1.yml, fixtures/autofix-namespace-missing-default-deny-netpol-fixed.yml, fixtures/autofix-namespace-missing-default-deny-netpol.yml, fixtures/autofix-single-unsupported-fixed_v1.yml, fixtures/autofix-single-unsupported_v1.yml, fixtures/autofix-unsupported-fixed_v1.yml, fixtures/autofix-unsupported_v1.yml, fixtures/preserve_comments-fixed_v2.yml, fixtures/preserve_comments_v2.yml, go.mod, go.sum
Now that goyaml v3 is out and supports comments, we can use that instead of the Shopify fork of goyaml v2.
~~There is one test that fails because of https://github.com/go-yaml/yaml/issues/508. Once that is fixed, we need to update the goyaml v3 dependency and then hopefully all the tests will pass!~~
Fixes #223
=> Replace Shopify/yaml with gopkg.in/yaml.v3

.travis.yml, Makefile
This switches Kubeaudit to Go1.12 and Go1.12 and ditches Go1.11
=> Switch travis to Go 1.12 and 1.13

cmd/kubernetes.go
We have an Azure Kubernetes cluster which has Azure authentication enabled. This failed silently in the latest stable release, `kubeaudit` just did nothing. Compiling from source led me to this:
```
FATA[0000] Could not get a kube client: No Auth Provider found for name "azure"
```
Turns out, supporting this is a simple import.
New feature :sparkles:
I ran `make build` and `./kubeaudit -c ~/.kube/aks.config all` to confirm it's working.
=> import azure auth module for AKS

README.md, cmd/commands/root.go, kubeaudit.go
The audit command will now return exit code 2 whenever any findings are found that have the type ERROR.
Fixes #257 
`make build`
=> feat(cli): return exit code 2 on error findings

auditors/apparmor/apparmor.go, auditors/apparmor/apparmor_test.go, auditors/apparmor/fixtures/apparmor-invalid-annotation.yml, docs/auditors/apparmor.md
If an apparmor annotation references a container that doesn't exist, the manifest will fail to apply. This PR adds a warning for this case.
=> Produce warning if apparmor annotation is invalid

.dockerignore, .goreleaser.yml, Dockerfile
This adds-in an updated Dockerfile and enables Docker image building & push to GitHub. :sparkles:
=> feat(docker): build Docker images too

internal/k8s/client.go, k8stypes/resources.go, printer.go, util_test.go
Hacky solution for the `apiVersion` and `kind` fields missing in local mode. The information seems to be missing in the SDK so I opened an [issue](https://github.com/kubernetes/client-go/issues/861) upstream. Basically, we know the `kind`  and `apiVersion` when we do `list` requests to the API so we can manually populate them. Note that the `apiVersion` may not be the same as the original `apiVersion` that was applied to the cluster. The kubernetes API converts all resources to the version the client requests, which in our case is the newest version of each resource.
Fixes #291
`make test-setup`
`kubectl apply -f internal/test/fixtures/all_resources`
`go run cmd/main.go apparmor`
`go run cmd/main.go apparmor -f internal/test/fixtures/all_resources/daemonset-v1beta1.yml`
=> Fix resource kind not known in local mode

auditors/asat/asat.go, auditors/asat/asat_test.go, auditors/asat/fix.go, auditors/asat/fix_test.go, auditors/asat/fixtures/service-account-token-false.yml, auditors/asat/fixtures/service-account-token-nil-and-no-name-and-default-sa.yml, auditors/asat/fixtures/service-account-token-true-and-default-sa.yml, auditors/netpols/netpols.go, auditors/netpols/util.go, docs/auditors/asat.md, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/runtime.go, k8stypes/resources.go, k8stypes/type_checks.go, k8stypes/types.go
Makes it so the `asat` auditor won't complain that token automounting is enabled if `automountServiceAccountToken: false` is set on the default ServiceAccount (and `automountServiceAccountToken` is not set to `true` in the PodSpec).
Fixes #290
=> Support automountServiceAccountToken on ServiceAccount

cmd/commands/root.go
Allows to run kubeaudit inside a cluster when a kubectl configuration is passed. 
Fixes #303 
I run it on my cluster with `.kubectl all -c /path/to/my/kubectl.conf`
=> Run Auditlocal, even when kubeaudit detected to run in a cluster.

cmd/commands/autofix.go
Fixes  #306 
Autofix was not overwriting the file as expected. The effective result is that we clear the file first before writing to it, rather than just overwriting, because there could be bits of the original file remaining at the end.
=> writes only to file and truncate it, so overwrite works as expected

docs/cluster.md
Found a small typo in the in-cluster job example.
Should be `automountServiceAccountToken` not `automountServiceAccount`.
```
pbpaste | kubectl apply -f -
error: error validating "STDIN": error validating data: ValidationError(Job.spec.template.spec): unknown field "automountServiceAccount" in io.k8s.api.core.v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
Also I think it would be best to set this to `true`, as kubeaudit actually needs the token and the rest of the CA mounted alongside it to communicate with the API Server. It'll fail otherwise even in clusters without RBAC enabled (at least in Docker Desktops for Mac's Kubernetes cluster), see logs below:
```
time="2020-10-12T10:07:28Z" level=fatal msg="Error auditing cluster in local mode" …
```
=> Fix Typo in InCluster Job Example

README.md, printer.go
Closes https://github.com/Shopify/kubeaudit/issues/311
After running `kubeaudit` and not having found errors with a given minimum severity to be reported, a message is printed to the cli in order to let the user know that no high-risk vulnerabilities were found.
I'm running `kubeaudit all -k config.yaml -f manifest.yaml` 
I'm using these files:
`manifest.yaml`
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: deployment
spec:
selector:
matchLabels:
name: deployment
template:
metadata:
labels:
name: deployment
annotations:
container.apparmor.security.beta.kubernetes.io/container: runtime/default
seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
containers:
- name: container
image: scratch
```
`config.yaml`:
```yaml
enabledAuditors:
apparmor: true
asat: true …
```
=> reports 0 vulnerabilies in case the check is successful

.travis.yml, README.md, auditors/all/all.go, config/config.yaml, docs/auditors/mountds.md, printer.go
Removes `mountds` from the `all` command (should be a no-op since the `mounts` command tests for the same things and more).
Also adds a deprecation notice at the top of the results (if using pretty print output)
> DEPRECATION NOTICE: The 'mountds' command is deprecated and will stop working in a future minor release. Please use the 'mounts' command instead. If you use 'all' no change is required
=> Deprecate mountds command

.goreleaser.yml, docs/release.md
It seems that goreleaser will now push up docker images even if set to draft mode.
=> Update release instructions

example_custom_test.go, example_test.go, kubeaudit.go
The examples for using kubeaudit as a package didn't work outside the kubeaudit repo because they had dependencies on internal packages. This adds an alias in the kubeaudit package root such that the relevant type can be imported outside of the kubeaudit repo.
Fixes https://github.com/Shopify/kubeaudit/issues/298
=> Remove example dependency on internal packages

auditors/apparmor/apparmor_test.go, auditors/apparmor/fixtures/apparmor-annotation-init-container-enabled.yml, auditors/apparmor/fixtures/apparmor-annotation-init-container-missing.yml, pkg/k8s/helpers.go
Adds support for `initContainers`. Current state is as follows and as described [here](https://github.com/Shopify/kubeaudit/issues/355#issue-959191623):
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template:
metadata:
annotations:
container.apparmor.security.beta.kubernetes.io/nginx: runtime/default
container.apparmor.security.beta.kubernetes.io/bb: runtime/default
spec:
initContainers:
- image: busybox
name: bb
command:
- /bin/echo
- hello
containers:
- image: nginx
name: nginx
```
```
$ kubeaudit apparmor -f deploy.yaml 
---------------- Results for ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx
--------------------------------------------
-- [error] AppArmorInvalidAnnotation
Message: …
```
=> pkg/k8s: add support for initContainer

docs/auditors/seccomp.md
Replace dead link to gardener.cloud seccomp tutorial with official kubernetes seccomp tutorial.
=> Fix deadlink in seccomp auditor docs

internal/k8sinternal/client.go, internal/k8sinternal/client_test.go, kubeaudit.go, util.go
If a group is not available on a server the `discovery.ServerPreferredResources` function returns  the list of preferred resources but also an [`ErrGroupDiscoveryFailed`](https://github.com/kubernetes/client-go/blob/v0.24.1/discovery/discovery_client.go#L331) error with the groups not available. 
This error can be ignored  because the unavailable resource types  should not be audited.
#
This is an example of a cluster with the `external.metrics.k8s.io` group not available:
```
$ kubectl  get apiservice v1beta1.external.metrics.k8s.io 
NAME                              SERVICE                    AVAILABLE                      AGE
v1beta1.external.metrics.k8s.io   my-custom-metrics-server   False (FailedDiscoveryCheck)   22d
```
```
$ kubectl  get --raw /apis/external.metrics.k8s.io/v1beta1 …
```
=> 🐛 Ignore groups not served  by the cluster

README.md, auditors/all/all.go, auditors/all/all_test.go, auditors/deprecatedapis/config.go, auditors/deprecatedapis/depreceatedapis.go, auditors/deprecatedapis/depreceatedapis_test.go, auditors/deprecatedapis/fixtures/cronjob.yml, cmd/commands/deprecatedapis.go, config/config.go, config/config.yaml, docs/auditors/deprecatedapis.md, internal/k8sinternal/client.go, internal/k8sinternal/scheme.go, internal/test/test.go
Fixes #408
Adds a new command `deprecatedapis` to find deprecated APIs of resources. It reports for all resources defined with a deprecated API the version since when it is deprecated  the deprecated version, the version where is removed and suggests the recommended API.
Here's a sample result:
```
$ kubeaudit deprecatedapis -f "auditors/deprecatedapis/fixtures/cronjob.yml"
---------------- Results for ---------------
apiVersion: batch/v1beta1
kind: CronJob
metadata:
name: hello
--------------------------------------------
-- [warning] DeprecatedAPIUsed
Message: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
Metadata:
DeprecatedMajor: 1
DeprecatedMinor: 21
RemovedMajor: 1
RemovedMinor: 25
ReplacementKind: CronJob
ReplacementGroup: batch/v1
``` …
=> ✨ Adds "deprecated apis" auditor

.github/autolabeler.yml, .github/labeler.yml, .github/probots.yml, .github/welcome.yml, .github/workflows/first-interaction.yml, .github/workflows/pr-labeler.yml
This PR migrates off probot and favors GH actions instead.
Caveats:
- [welcome](https://github.com/marketplace/actions/first-interaction) => we're missing a celebration when folks merge their PRs. I don't think this field is supported by the GH action
- triage-new-issues => There is no equivalent. Triaging issues will have to be done manually (if we think it's worth it, we can write our own action for that in a a follow-up PR)
workflow / dev / contributions
=> uses gh actions instead of probot

docs/release.md
This PR slightly updates the docs on making a release. I no longer have Docker Desktop installed and realized I can use `colima` as an alternative and I think it'd be nice to let others know that this is an option
=> updates release instructions

internal/sarif/sarif.go
This is to add the Metadata field/info to the sarif. We currently display this info on the CLI. but it was missing on the sarif. Here's an example of what it will look like on Github UI:
=> adds metadata to sarif result

.github/workflows/ci.yml, README.md, internal/test/test.go, kubeaudit_test.go, test.sh
Instead of running tests in a "Kind" environment by default, explicitly enable Kind. This prevents accidentally running cluster tests against a production cluster with `go test ./...` (as opposed to `make test` which would first activate the Kind cluster).
=> By default, test without Kind
